# Programação Dinâmica

Bibliografia: Seção 6.3 de [Dasgupta-Papadimitriou-Vazirani](http://algorithmics.lsi.upc.edu/docs/Dasgupta-Papadimitriou-Vazirani.pdf)


## Distância de edição

Considere duas palavras:

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.tg .tg-us36{border-color:inherit;vertical-align:top}
</style>
<table class="tg">
  <tr>
    <td class="tg-us36">C</td>
    <td class="tg-us36">A</td>
    <td class="tg-us36">C</td>
    <td class="tg-us36">H</td>
    <td class="tg-us36">O</td>
    <td class="tg-us36">R</td>
    <td class="tg-us36">R</td>
    <td class="tg-us36">O</td>
    <td class="tg-us36"></td>
  </tr>
  <tr>
    <td class="tg-us36">C</td>
    <td class="tg-us36">H</td>
    <td class="tg-us36">U</td>
    <td class="tg-us36">R</td>
    <td class="tg-us36">R</td>
    <td class="tg-us36">A</td>
    <td class="tg-us36">S</td>
    <td class="tg-us36">C</td>
    <td class="tg-us36">O</td>
  </tr>
</table>

Quão distante é a palavra "CACHORRO" da palavra "CHURRASCO"?

### Distância de edição

Considere as seguintes operações:
- **Substituição:** Trocar uma letra por outra.

Por exemplo, podemos transformar "CALMA" em "PALMA" substituindo o C por P.

- **Remoção:** Remover uma letra.

Por exemplo, podemos transformar "CALMA" em "ALMA" removendo o C.

- **Inserção:** Inserir uma letra.

Por exemplo, podemos transformar "PALMA" em "PALMAS" inserindo um S.

**DEFINIÇÃO**: A **distância de edição** entre uma palavra $x$ e uma palavra $y$ é o menor número de operações de substituição, remoção e inserção necessárias para transformar $x$ em $y$.

Por exemplo, a distância de edição de CACHORRO para CHURRASCO é $6$.

- CACHORRO
- ACHORRO -> remove C
- CHORRO -> remove A
- CHURRO -> substitui O por U
- CHURRAO -> insere A
- CHURRASO -> insere S
- CHURRASCO -> insere C

> **Exercício:** Qual é distância de edição entre as seguintes palavras? Mostre como transfomar uma na outra.
>
> a) azul e anzol
>
> b) exponencial e polinomial
>
> c) introdução e conclusão
>
> d) aluno e alumínio

Usamos $\textrm{dist}(x,y)$ para indicar a distância de edição entre palavras $x$ e $y$.

## Problema (EDIT-DIST)
#### Entrada: Duas palavras $x$ e $y$
#### Saída: dist($x,y$)

### Alinhamentos

**DEFINIÇÃO (INFORMAL):** Um **alinhamento** entre palavras $x$ e $y$ é "maneira" de escrever $x$ e $y$ uma em cima da outra. Por exemplo, para "CACHORRO" e "CHURRASCO", um possível alinhamento é:

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.tg .tg-us36{border-color:inherit;vertical-align:top}
</style>
<table class="tg">
  <tr>
    <td class="tg-us36">C</td>
    <td class="tg-us36">A</td>
    <td class="tg-us36">C</td>
    <td class="tg-us36">H</td>
    <td class="tg-us36">O</td>
    <td class="tg-us36">R</td>
    <td class="tg-us36">R</td>
    <td class="tg-us36">-</td>
    <td class="tg-us36">-</td>
    <td class="tg-us36">-</td>
    <td class="tg-us36">O</td>
  </tr>
  <tr>
    <td class="tg-us36">C</td>
    <td class="tg-us36">-</td>
    <td class="tg-us36">-</td>
    <td class="tg-us36">H</td>
    <td class="tg-us36">U</td>
    <td class="tg-us36">R</td>
    <td class="tg-us36">R</td>
    <td class="tg-us36">A</td>
    <td class="tg-us36">S</td>
    <td class="tg-us36">C</td>
    <td class="tg-us36">O</td>
  </tr>
</table>

O **custo** de um alinhamento é o número de "-" mais o número de letras que estão alinhadas, mas são diferentes.

O custo do alinhamento acima é $6$.

> **Exercício:** para cada um dos alinhamentos abaixo, diga qual é o custo.
>
> (a)
> 
<table class="tg">
  <tr>
    <td class="tg-us36">-</td>
    <td class="tg-us36">A</td>
    <td class="tg-us36">L</td>
    <td class="tg-us36">M</td>
    <td class="tg-us36">A</td>
  </tr>
  <tr>
    <td class="tg-us36">C</td>
    <td class="tg-us36">A</td>
    <td class="tg-us36">L</td>
    <td class="tg-us36">M</td>
    <td class="tg-us36">O</td> </tr>
</table>
> (b)
> 
<table class="tg">
  <tr>
    <td class="tg-us36">-</td>
    <td class="tg-us36">-</td>
    <td class="tg-us36">P</td>
    <td class="tg-us36">O</td>
    <td class="tg-us36">L</td>
    <td class="tg-us36">I</td>
    <td class="tg-us36">N</td>
    <td class="tg-us36">O</td>
    <td class="tg-us36">M</td>
    <td class="tg-us36">I</td>
    <td class="tg-us36">A</td>
    <td class="tg-us36">L</td>
  </tr>
  <tr>
    <td class="tg-us36">E</td>
    <td class="tg-us36">X</td>
    <td class="tg-us36">P</td>
    <td class="tg-us36">O</td>
    <td class="tg-us36">N</td>
    <td class="tg-us36">E</td>
    <td class="tg-us36">N</td>
    <td class="tg-us36">-</td>
    <td class="tg-us36">C</td>
    <td class="tg-us36">I</td>
    <td class="tg-us36">A</td>
    <td class="tg-us36">L</td>
  </tr>
</table>
> (c)
> 
<table class="tg">
  <tr>
    <td class="tg-us36">M</td>
    <td class="tg-us36">U</td>
    <td class="tg-us36">L</td>
    <td class="tg-us36">T</td>
    <td class="tg-us36">I</td>
    <td class="tg-us36">P</td>
    <td class="tg-us36">L</td>
    <td class="tg-us36">O</td>
  </tr>
  <tr>
    <td class="tg-us36">D</td>
    <td class="tg-us36">U</td>
    <td class="tg-us36">-</td>
    <td class="tg-us36">-</td>
    <td class="tg-us36">-</td>
    <td class="tg-us36">P</td>
    <td class="tg-us36">L</td>
    <td class="tg-us36">O</td>  </tr>
</table>
> (d)
> 
<table class="tg">
  <tr>
    <td class="tg-us36">-</td>
    <td class="tg-us36">A</td>
    <td class="tg-us36">N</td>
    <td class="tg-us36">D</td>
    <td class="tg-us36">-</td>
    <td class="tg-us36">A</td>
    <td class="tg-us36">R</td>
    <td class="tg-us36">-</td>
    <td class="tg-us36">I</td>
    <td class="tg-us36">L</td>
    <td class="tg-us36">H</td>
    <td class="tg-us36">O</td>
  </tr>
  <tr>
    <td class="tg-us36">M</td>
    <td class="tg-us36">A</td>
    <td class="tg-us36">L</td>
    <td class="tg-us36">T</td>
    <td class="tg-us36">R</td>
    <td class="tg-us36">A</td>
    <td class="tg-us36">-</td>
    <td class="tg-us36">P</td>
    <td class="tg-us36">I</td>
    <td class="tg-us36">L</td>
    <td class="tg-us36">H</td>
    <td class="tg-us36">O</td>
  </tr>
</table>

## Problema (ALIN)
#### Entrada: duas palavras $x$ e $y$
#### Soluções viáveis: todos os possíveis alinhamentos entre $x$ e $y$
#### Objetivo: minimizar o custo

## Como (ALIN) e (EDIT-DIST) se relacionam?

O custo do melhor alinhamento entre $x$ e $y$ é $\textrm{dist}(x,y)$.

Por que???

Porque cada alinhamento pode ser reproduzido através de operações de substituição, remoção e inserção, e vice-versa.

<table class="tg">
  <tr>
    <td class="tg-us36">C</td>
    <td class="tg-us36">A</td>
    <td class="tg-us36">C</td>
    <td class="tg-us36">H</td>
    <td class="tg-us36">O</td>
    <td class="tg-us36">R</td>
    <td class="tg-us36">R</td>
    <td class="tg-us36">-</td>
    <td class="tg-us36">-</td>
    <td class="tg-us36">-</td>
    <td class="tg-us36">O</td>
  </tr>
  <tr>
    <td class="tg-us36">C</td>
    <td class="tg-us36">-</td>
    <td class="tg-us36">-</td>
    <td class="tg-us36">H</td>
    <td class="tg-us36">U</td>
    <td class="tg-us36">R</td>
    <td class="tg-us36">R</td>
    <td class="tg-us36">A</td>
    <td class="tg-us36">S</td>
    <td class="tg-us36">C</td>
    <td class="tg-us36">O</td>
  </tr>
</table>
Equivale a $6$ operações:
- CACHORRO
- CCHORRO: remova A
- CHORRO: remova C
- CHURRO: substitua O por U
- CHURRAO: insira A
- CHURRASO: insira S
- CHURRASCO: insira C

> **Exercício:** Para cada um dos alinhamentos no exercício anterior, mostre quais operações devem ser feitas.

## Solução com programação dinâmica

Considere que as palavras recebidas são $x_1x_2x_m$ e $y_1y_2...y_n$

### Subproblemas

#### Subproblema E(i,j): calcular custo do melhor alinhamento de $x[1..i]$ com $y[1...j]$

Para $i=0$, consideramos $x[1...0]$ como a palavra vazia. Ou seja,
- $E(0, j) = j$ -- custo da inserção de $j$ caracteres
- $E(i,0) = i$ -- custo da inserção de $i$ caracteres

#### Resposta final: E(m, n) 
#### Como calcular $E(i,j)$?

para as últimas letras $x_i$ e $y_j$ temos 3 possibilidades:

1) $x_i$ é alinhado com $-$: o custo é $1+E(i-1,j)$

2) $y_j$ é alinhado com $-$: o custo é $1+E(i,j-1)$

3) $x_i$ é alinhado com $y_j$: o custo é $E(i-1,j-1)$ mais 1 no caso em que $x_i \neq y_j$

Assim, $E(i,j) = \min(1+E(i-1,j), 1+E(i,j-1), E(i-1,j-1) + diff(i,j))$, onde $diff(i,j)=1$ se $x_i\neq y_j$ e $0$, caso contrário.

Note que $E(i,j)$ depende apenas dos valores $E(i-1,j), 1+E(i,j-1), E(i-1,j-1)$.

Assim, temos o seguinte pseudocódigo:

```
para i de 0 a m faça E(i,0) = i
para j de 0 a n faça E(0,j) = j
para i de 1 a m faça
    para j de 1 a n faça
        E(i,j) = min(1+E(i-1,j), 1+E(i,j-1), E(i-1,j-1) + diff(i,j))

```

>**Exercício:** Rodar o pseudocódigo para os pares a seguir, basta mostrar a matriz $E$ final.
> (a) "caule" e "aula"
>
> (b) "andarilho" e "maltrapilho"
>
> (c) "deserto" e "prefeito"
>
> (d) "grampo" e "garimpo"

Consumo de tempo: $\Theta(nm)$

Consumo de espaço: $\Theta(nm)$

In [9]:
import sys
!{sys.executable} -m pip install numpy

In [10]:
from numpy import * 

In [42]:
def preenche(x,y):
    m = len(x)
    n = len(y)
    #Cria matriz (m+1)x(n+1) inicializada com 0's
    E = [0]*(m+1)*(n+1) 
    E = reshape(E, (m+1,n+1)) 
    
    for i in range(m+1):
        E[i][0] = i
        
    for j in  range(n+1):
        E[0][j] = j
        
    for i in range(1,m+1):
        for j in  range(1,n+1):
            d = 0
            if x[i-1]!=y[j-1]:
                d = 1
            E[i][j] = min(1+ E[i-1][j], 1+ E[i][j-1], E[i-1][j-1]+d)
    print(E)
    print('Resposta: '+str(E[m][n]))

In [43]:
preenche("cachorro", "churrasco")

[[0 1 2 3 4 5 6 7 8 9]
 [1 0 1 2 3 4 5 6 7 8]
 [2 1 1 2 3 4 4 5 6 7]
 [3 2 2 2 3 4 5 5 5 6]
 [4 3 2 3 3 4 5 6 6 6]
 [5 4 3 3 4 4 5 6 7 6]
 [6 5 4 4 3 4 5 6 7 7]
 [7 6 5 5 4 3 4 5 6 7]
 [8 7 6 6 5 4 4 5 6 6]]
Resposta: 6


## Como recuperar o alinhamento de menor custo?

Para cada $(i,j)$, guarda $p(i,j)$ que indica se o mínimo veio de  $1+ E[i-1][j]$, $1+ E[i][j-1]$ ou de $E[i-1][j-1]$.

> **Exercício:** Modifique preenche(x,y) ou o pseudocódigo para que o melhor alinhamento seja impresso ao final.

## Recursão memoizada

In [57]:
def preenche2(x,y):
    m = len(x)
    n = len(y)
    #Cria matriz (m+1)x(n+1) inicializada com 0's
    E = [0]*(m+1)*(n+1) 
    E = reshape(E, (m+1,n+1)) 
    preencheRec(E, m, n,x,y)
    print(E)
    print(E[m][n])
    
def preencheRec(E, i, j,x,y):
    if E[i][j]!=0:
        return E[i][j]
    if i==0:
        E[i][j]=j
    elif j==0:
        E[i][j]=i
    else:
        d = 0
        if x[i-1]!=y[j-1]:
            d = 1
        E[i][j] = min(1+ preencheRec(E,i-1,j,x,y), 1+ preencheRec(E,i,j-1,x,y), preencheRec(E,i-1,j-1,x,y)+d)
    return E[i][j]

In [58]:
preenche2("cachorro","churrasco")

[[0 1 2 3 4 5 6 7 8 9]
 [1 0 1 2 3 4 5 6 7 8]
 [2 1 1 2 3 4 4 5 6 7]
 [3 2 2 2 3 4 5 5 5 6]
 [4 3 2 3 3 4 5 6 6 6]
 [5 4 3 3 4 4 5 6 7 6]
 [6 5 4 4 3 4 5 6 7 7]
 [7 6 5 5 4 3 4 5 6 7]
 [8 7 6 6 5 4 4 5 6 6]]
6


> **Exercício:** Mostrar a árvore com as chamadas da função ```preencheRec``` para os pares de palavras a seguir
>
> (a) "caule" e "aula"
>
> (b) "andarilho" e "maltrapilho"
>
> (c) "deserto" e "prefeito"
>
> (d) "grampo" e "garimpo"

## Economizando espaço

Ideia: só precisamos de 2 linhas, pois cada $E(i,j)$ depende apenas da linha atual e da linha anterior!

In [48]:
def preenche3(x,y):
    m = len(x)
    n = len(y)
    #Cria matriz (m+1)x(n+1) inicializada com 0's
    E = [0]*(n+1)*2
    E = reshape(E, (2,n+1)) 
    
    for j in range(n+1):
        E[0][j] = j
        
    for i in range(1,m+1):
        atual=0
        ant = 1
        if i%2==1: 
            atual=1
            ant = 0
        E[atual][0]=i
        for j in  range(1,n+1):
            d = 0
            if x[i-1]!=y[j-1]:
                d = 1
            E[atual][j] = min(1+ E[ant][j], 1+ E[atual][j-1], E[ant][j-1]+d)
    print(E)
    print('Resposta: '+str(E[atual][n]))

In [47]:
preenche3("cachorro","churrasco")
preenche("cachorro","churrasco")

[[8 7 6 6 5 4 4 5 6 6]
 [7 6 5 5 4 3 4 5 6 7]]
Resposta: 6
[[0 1 2 3 4 5 6 7 8 9]
 [1 0 1 2 3 4 5 6 7 8]
 [2 1 1 2 3 4 4 5 6 7]
 [3 2 2 2 3 4 5 5 5 6]
 [4 3 2 3 3 4 5 6 6 6]
 [5 4 3 3 4 4 5 6 7 6]
 [6 5 4 4 3 4 5 6 7 7]
 [7 6 5 5 4 3 4 5 6 7]
 [8 7 6 6 5 4 4 5 6 6]]
Resposta: 6


>**Exercício:** Implementar a programação dinâmica com apenas 1 vetor (mais espaço $O(1)$).

# Mochila inteira

Bibliografia: Seção 6.4 de [Dasgupta-Papadimitriou-Vazirani](http://algorithmics.lsi.upc.edu/docs/Dasgupta-Papadimitriou-Vazirani.pdf)


#### Problema (INT-MOCHILA):
#### Entrada: um inteiro $n$, um inteiro $W$ (capacidade), pesos inteiros $(w_1,\dotsc, w_n)$ e valores $(v_1,\dotsc, v_n)$
#### Soluções viáveis: $(x_1,\dotsc, x_n)$, onde $x_i=0$ ou $x_i=1$ para cada $i$ e $\sum_{i=1}^n x_iw_i \leq W$
#### Objetivo: maximizar $\sum_{i=1}^n x_iv_i$

Já vimos a versão fracionária (em que $0\leq x_i\leq 1$). Como já discutimos, a estratégia de considerar os itens de acordo com custo benefício não funciona.

> **Exercício:** Mostrar um exemplo em que a estratégia gulosa que vimos para a mochila fracionária não devolve o melhor valor para a mochila inteira.

## Subproblema K(W', j): o maior valor para uma mochila de capacidade $W'$ e itens $1,\dotsc, j$

- $K(0,j) = 0$ para todo $j$
- $K(W', 0) = 0$ para todo $W'$
- para $W'>0$ e $j>0$, para $K(W',j)$ temos duas opções:

1) o item $j$ é incluso: valor $v_j + K(W'-w_j, j-1)$ (somente se $w_j\leq W'$)

2) o item $j$ **não** é incluso: valor $K(W', j-1)$

Assim, 
$$
K(W',j) =
\begin{cases}
0,&\text{ se }j=0\text{ ou }W'=0\\
K(W',j-1),&\text{ se }w_j>W'\\
\max\{v_j+ K(W'-w_j,j-1), K(W',j-1)\},&\text{ caso contrário}
\end{cases}
$$


Assim, temos o seguinte pseudocódigo:
```
para W' de 0 a W faça K[W'][0]=0
para j de 0 a n faça K[0][j]=0

para W' de 1 a W
    para j de 1 a n
       se w_j > W'
          K[W'][j]=K[W'][j-1]
       senão
          K[W'][j] = max(v_j+K[W'-w_j][j-1], K[W'][j-1])
```


In [63]:
def mochila(W,w,v):
    n = len(w)
    K = [0]*(W+1)*(n+1)
    K = reshape(K,(W+1,n+1))
    for Wp in range(1,W+1):
        for j in range (1,n+1):
            if w[j-1]>Wp: 
                K[Wp][j]=K[Wp][j-1]
            else:
                K[Wp][j] = max(v[j-1]+K[Wp-w[j-1]][j-1], K[Wp][j-1])
    print(K)

In [67]:
mochila(10,[2,3,2,4],[4,4,3,4])

[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  4  4  4  4]
 [ 0  4  4  4  4]
 [ 0  4  4  7  7]
 [ 0  4  8  8  8]
 [ 0  4  8  8  8]
 [ 0  4  8 11 11]
 [ 0  4  8 11 11]
 [ 0  4  8 11 12]
 [ 0  4  8 11 12]]


> **Exercício:** Modifique o código ```mochila``` para que use uma matriz de $K$ de apenas 2 colunas ou de apenas 2 linhas.